#!/usr/bin/perl
# Copyright 2012 by Robert Lange <robert.lange@s1999.tu-chemnitz.de>
# Inspired by script "dpkg", Copyright 2006 by Willi Mann <willi@wm1.at>
#                and "sshd", Copyright (c) 2008 Kirk Bauer
###########################################################################
# $Id$
###########################################################################
# $Log$
#
###########################################################################

########################################################
## Copyright 2012 by Robert Lange <robert.lange@s1999.tu-chemnitz.de>
## Inspired by script "dpkg", Copyright 2008 by Willi Mann <willi@wm1.at>
##                and "sshd", Copyright (c) 2008 Kirk Bauer
## Covered under the included MIT/X-Consortium License:
##    http://www.opensource.org/licenses/mit-license.php
## And in parallel under GNU Public License
#########################################################

use strict;
# Needed? use Logwatch ':all';

my $Debug = $ENV{'LOGWATCH_DEBUG'} || 0;
# Not used, see sshd my $Detail = $ENV{'LOGWATCH_DETAIL_LEVEL'} || 0;

# Each variable is separated by website
my %install = ();
my %enable  = ();
my %disable = ();
my %unknown = ();
my %php     = ();
# This dummy hash just keeps track about all possible sites
my %avlsites = ();


# Parser variables - correspondent to following drupal log format specifiers
my $line;
my $site;        # !base_url
my $timestamp;   # !timestamp
my $cat;         # !type - Category
my $ip;          # !ip
my $requri;      # !request_uri
my $uid;         # !uid
my $msg;         # !message



if ( $Debug >= 5 ) {
	print STDERR "\n\nDEBUG: Inside drupal Filter \n\n";
}

while(my $line=<STDIN>) {
    if ( $Debug >= 5 ) {
	print STDERR "DEBUG: Verbatim log line: $line";
    }
    chomp $line;
    ## if ( # Matches to ignore
    ## 	($line =~ /^pam_succeed_if: requirement "uid < 100" (not|was) met by user /) or
    ##     # ...
    ## ) {
    ## } elsif
    # *** Break down the log entry into pieces
    if (not ( ($site, $timestamp, $cat, $ip, $requri, $uid, $msg) = 
	( $line =~ /^(.+)|(\d+)|([\w\d]+)|([\d\.]+)|(.+)|.+|(\d+)|(.*)|(.+)$/) )) {
	print STDERR "ERROR: Failed to break down drupal log: $line\n";
	print STDERR "ERROR: Did you configured the log format correctly?\n";
	exit(1);
    }
    $avlsites{$site} = 1;

    # *** First of all, System actions
    if ($cat eq "system" ) {
	# *** Module Management: Install, Enable, Disable
	# Templates:
	# \d+|system|10.0.2.2|http://website.org:8080/admin/modules/list/confirm?render=overlay|http://website.org:8080/admin/modules?render=overlay|1||syslog module installed.
	# \d+|system|10.0.2.2|http://website.org:8080/admin/modules/list/confirm?render=overlay|http://website.org:8080/admin/modules?render=overlay|1||syslog module enabled.
	# \d+|system|10.0.2.2|http://website.org:8080/admin/modules/list/confirm?render=overlay|http://website.org:8080/admin/modules?render=overlay|1||dblog module disabled.
	# Split down the log message into module and action
	if ( my ( $module, $action) = ( $msg =~ /^(\w+) module (disabled|enabled|installed).$/ ) ) {
	    if ($action eq "installed") {
		push @{$install{$site} }, $module;
	    } elsif ($action eq "enabled") {
		push @{$enable{$site} }, $module;
	    } elsif ($action eq "disabled") {
		push @{$disable{$site} }, $module;
	    } else {
		# Assert; this line cannot be reached
		print STDERR "ERROR: Failure in Module management extraction for line \"$line\". This is a bug in the logwatch drupal script.";
	    }
	} else {  # Unknown action
	    # This we don't know at all
	    push @{ $unknown{$site} }, "Unknow system action: $msg";
	}

    # *** Now take care about php messages
    } elsif ( $cat eq "php" ) {
	push @{$php{$site} }, $msg;
    } else {
	# This we don't know at all
	push @{ $unknown{$site} }, $line;
    }
}


# ** Output collected information
foreach $site (keys %avlsites) {
    # For each site
    print $site . "\n*************\n\n";

    my @k = ( "Modules Installed" , \@install{$site},
	      "Modules Enabled" , \@enable{$site},
	      "Modules Disabled" , \@disable{$site},
	      "Unmatched Entries", \@unknown{$site} );

    while (@k > 0) {
	my $text = shift @k;
	my $array = shift @k;
	if(@$array) {
		print "\n$text:\n";
		foreach my $line (sort @$array) {
			print "   $line\n";
		}

	}
    }
}


